name: test-workflow

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      BROWSER:
        description: Browser
        required: false
        default: Opera
      OS:
        description: OS
        required: false
        default: macOS 
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_ENDPOINT: https://testing.qatools.cloud
  ALLURE_PROJECT_ID: 1936
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "allure-results"

jobs:
  autotests: 
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://testing.qatools.cloud/
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 1936
          
      - name: Run tests
        run: allurectl watch -- pytest --alluredir=${ALLURE_RESULTS} --capture=no
        env:
          BROWSER: ${{ github.event.inputs.BROWSER}}
          OS: ${{ github.event.inputs.OS}}
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
          ALLURE_RESULTS: "allure-results"